version: "3.9"
services:
  api1: &api # API - Instância 01
    # build:
    #   context: .
    #   dockerfile: Srv/Dockerfile
    image: dpcprofile/rinha_csharp_v2:latest
    hostname: api1
    depends_on:
      - db
    environment:
      ConnectionStrings__postgresql: "User ID=admin;Password=123;Server=db;Port=5432;Database=rinha;"
    ports:
      - "80:80"
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "0.250GB"

  api2: # API - Instância 02
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: nginx:alpine
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "0.1GB"
  
  db:
    image: postgres:16-alpine
    hostname: db
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
  
networks:
  default:
    driver: bridge
    name: rinha_v2