@producao = http://localhost:9999
@desenv = http://localhost:5229

###
GET {{producao}}/contagem-pessoas

###
POST {{producao}}/pessoas
Content-Type: application/json

{
    "nome": "Daniel",
    "Apelido": "deniels",
    "Nascimento": "1997-09-17",
    "stack" : ["C#", "Python"]
}

###
POST {{producao}}/pessoas
Content-Type: application/json

{
    "nome": "Beatriz",
    "apelido": "bia",
    "Nascimento": "1985-09-23"
}

###
GET {{producao}}/pessoas?t=

###
GET {{producao}}/pessoas?t=Py

###
GET {{producao}}/pessoas/238f77cc-4fbf-4adf-896b-86b677bf3139

#==========================================================================
###
GET {{desenv}}/contagem-pessoas

###
GET {{desenv}}/pessoas/1c076a85-22ff-4cf1-b156-b2f063a787c9

###
GET {{desenv}}/pessoas/1

###
GET {{desenv}}/pessoas?t=Py

###
GET {{desenv}}/pessoas?t=

###
POST {{desenv}}/pessoas
Content-Type: application/json

{
    "nome": "Daniel",
    "Apelido": "deniels",
    "Nascimento": "1997-09-17",
    "stack" : ["C#", "Python"]
}

###
POST {{desenv}}/pessoas
Content-Type: application/json

{
    "nome": "Beatriz",
    "apelido": "biaP",
    "Nascimento": "1985-09-23"
}